---
title: "Conclusion"
output:
  html_document:
    includes:
      in_header: "favicon.html"
---
<font size = 3><p align = justify>
Overall, only 12.87% (17/132) of participants in our study cheated. For those who did cheat, the average magnitude of cheating amounted to the over-reporting of just three matrices, thus constituting a relatively low degree of dishonesty. Besides the fact that many participants may not have recognized the opportunity to cheat, we largely attribute the observed low levels of cheating behavior to a probable selection bias. Meaning, we believe that most participants agreed to be in our study in an effort to help us out with this school-related project, and not in order to maximize their own utility. With this motive in mind, many participants may have in fact recognized the opportunity to cheat, but believed that exploiting it would be a slight to us. </p>

<p align = justify>With regards to our first hypothesis, we found that there was no statistically significant difference in the frequency nor in the magnitude of cheating between participants who were assigned to the self-control depletion and control treatment groups. This possibly hints at the ineffectiveness of our depletion task, for which we have no true manipulation check, but it also calls into question the finding of both Mead et al., (2009) and Gino et al., (2011), as these two studies and their findings directly motivated Hypothesis 1.</p>

<p align = justify>Similarly, with regards to our second hypothesis, we found that there was no statistically significant difference in the frequency of cheating between participants assigned to loss and gain treatment conditions. This possibly means that our implementation of the loss/gain framing conditions, and the nuance between them in our experimental design, were not salient enough, and/or that Grolleau et al. (2016)’s findings are dubious, again because Hypothesis 2 was born out of said findings.</p>

<p align = justify>We did however find there to be a statistically significant difference between the loss and gain framing treatment groups with respect to the amount participants cheated. This suggests that while loss framing may not lead more people to cheat than gain framing, for those who do decide to cheat, loss framing may lead them to cheat to a greater degree. However, we are wary of drawing any broad conclusions from this finding, being that the sample size studied was so small (i.e. n = 17).</p>

<p align = justify>In line with these findings, for our third hypothesis we found that there was no statistically significant difference in the frequency of cheating across the four treatment groups we tested. However, in terms of the magnitude of cheating, we did find a statistically significant difference between the four groups. With that said though, because our study observed just 17 instances of cheating, it is ultimately just too under-powered to take this finding very seriously.</p>

<p align = justify>Overall, there is little evidence supporting the notion of any interaction effects between self-control depletion/non-depletion and loss/gain framing. While these findings are disappointing, they actually do align with and corroborate the growing body of "reproducibility"/"replication" research in the domain of self-control depletion (e.g. [Hagger et al., 2016](https://journals.sagepub.com/doi/abs/10.1177/1745691616652873])), that provides very strong evidence of null effects. Again though, it must be stressed that due to the low number of observations and other design limitations, more work should be done in the future by researchers to really solidify our understanding of such effects. Along these lines, we would ideally see this experiment administered under proper lab conditions where data collection is a bit more systematized and a bit less onerous; where participants would come to us instead of us soliciting them. We are also highly interested in extending the present study to consider the effects of cognitive depletion versus those of [cognitive load](https://onlinelibrary.wiley.com/doi/abs/10.1207/s15516709cog1202_4) on cheating.</p>
